name: Build and Release

on:
  workflow_dispatch:


# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Increase Patch version
        run: |
        pwd
        
        #   CURRENT_VERSION=$(xmllint --xpath "//*[local-name()='project']/*[local-name()='version']/text()" pom.xml)
        #   echo $CURRENT_VERSION

        #   # Extract the patch version using awk
        #   PATCH=$(echo "$CURRENT_VERSION" | awk -F. '{print $3}')
        #   echo $PATCH
        #   # Increase the patch version
        #   NEW_PATCH=$((PATCH + 1))
        #   echo $NEW_PATCH
        #   # # Update the version in the pom.xml
        #   # sed -i "s/<version>$CURRENT_VERSION<\/version>/<version>$MAJOR.$MINOR.$NEW_PATCH<\/version>/" pom.xml
        # shell: bash


      # - name: Compile code and package artifact
      #   run: mvn clean package

      # - name: Create artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: myapp-artifact
      #     path: target/myapp-*.jar
